# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.23
# 
# >> macros
# << macros

Name:       xorg-x11-drv-mtev
Summary:    Multitouch input driver for Xserver
Version:    0.1.13
Release:    1
Group:      System/X Hardware Support
License:    GPLv2
URL:        http://gitorious.org/xorg/xf86-input-mtev
Source0:    %{name}-%{version}.tar.gz
Source1:    60-cando-mtev.conf
Source2:    70-sitronix-mtev.conf
Source3:    80-Hanvon-mtev.conf
Source4:    90-ILI-mtev.conf
Source5:    91-ecss10ot3.conf
Source100:  xorg-x11-drv-mtev.yaml
Patch0:     apis-match-for-xserver-1.10.1.patch     	
Patch1:     add-orientation-support.patch	    
BuildRequires:  pkgconfig(xorg-server)
BuildRequires:  pkgconfig(xkbfile)
BuildRequires:  pkgconfig(xproto)
BuildRequires:  pkgconfig(inputproto)
BuildRequires:  pkgconfig(xrandr)
BuildRequires:  pkgconfig(randrproto)
BuildRequires:  pkgconfig(xextproto)
BuildRequires:  pkgconfig(mtdev)


%description
This is a xserver-xorg input driver for devices supporting Linux Multi-Touch protocol

%prep
%setup -q -n %{name}-%{version}
# apis-match-for-xserver-1.10.1.patch
%patch0 -p1

# add-orientation-support.patch
%patch1 -p1

# >> setup
# << setup

%build
# >> build pre
# << build pre


make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
mkdir -p %{buildroot}/etc/X11/xorg.conf.d
install -p -m 644 %{SOURCE1} %{buildroot}/etc/X11/xorg.conf.d
install -p -m 644 %{SOURCE2} %{buildroot}/etc/X11/xorg.conf.d
install -p -m 644 %{SOURCE3} %{buildroot}/etc/X11/xorg.conf.d
install -p -m 644 %{SOURCE4} %{buildroot}/etc/X11/xorg.conf.d
install -p -m 644 %{SOURCE5} %{buildroot}/etc/X11/xorg.conf.d
# << install post






%files
%defattr(-,root,root,-)
# >> files
%(pkg-config xorg-server --variable=moduledir )/input/mtev.so
%config  /etc/X11/xorg.conf.d/60-cando-mtev.conf
%config  /etc/X11/xorg.conf.d/70-sitronix-mtev.conf
%config  /etc/X11/xorg.conf.d/80-Hanvon-mtev.conf
%config  /etc/X11/xorg.conf.d/90-ILI-mtev.conf
%config  /etc/X11/xorg.conf.d/91-ecss10ot3.conf
# << files


